project_id = "dtwqmrmtzfhczvjggmct"

[functions.create-first-admin]
verify_jwt = false

[functions.admin-signup]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.start-instance]
verify_jwt = false

[functions.get-media-urls]
verify_jwt = false

[functions.generate-custom-quest]
verify_jwt = false

[functions.public-generate-quest]
verify_jwt = false
