project_id = "dtwqmrmtzfhczvjggmct"

[functions.create-first-admin]
verify_jwt = false

[functions.admin-signup]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.start-instance]
verify_jwt = false
