ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS place_id text UNIQUE;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS category_google text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS category_ai text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS rating numeric;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS reviews_count integer DEFAULT 0;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS district text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS souks_nearby text[] DEFAULT '{}';
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS description_short text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS history_context text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS local_anecdote text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS instagram_spot boolean DEFAULT false;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS nearby_restaurants jsonb DEFAULT '[]';
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS nearby_pois_data jsonb DEFAULT '[]';
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS riddle_easy text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS riddle_medium text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS challenge text;
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS google_raw jsonb DEFAULT '{}';
ALTER TABLE medina_pois ADD COLUMN IF NOT EXISTS enrichment_status text DEFAULT 'pending';
CREATE INDEX IF NOT EXISTS idx_medina_pois_place_id ON medina_pois(place_id);
CREATE INDEX IF NOT EXISTS idx_medina_pois_enrichment_status ON medina_pois(enrichment_status);